In [2]:
import numpy as np
import pandas as pd

# 1

Даны значения величины заработной платы заемщиков банка (zp) и значения их поведенческого кредитного скоринга (ks): zp = [35, 45, 190, 200, 40, 70, 54, 150, 120, 110], ks = [401, 574, 874, 919, 459, 739, 653, 902, 746, 832]. Используя математические операции, посчитать коэффициенты линейной регрессии, приняв за X заработную плату (то есть, zp - признак), а за y - значения скорингового балла (то есть, ks - целевая переменная). Произвести расчет как с использованием intercept, так и без.

In [3]:
zp = np.array([35, 45, 190, 200, 40, 70, 54, 150, 120, 110])
ks = np.array([401, 574, 874, 919, 459, 739, 653, 902, 746, 832])

с использованием intercept

In [4]:
b = (np.mean(zp*ks) - np.mean(zp)*np.mean(ks)) / (np.mean(zp**2)-np.mean(zp)**2)
b

2.620538882402765

In [5]:
a = np.mean(ks)-b*np.mean(zp)
a

444.1773573243596

In [ ]:
y_ = 444.18 + 2.62*x

матричный способ

In [6]:
zp1 = zp.reshape((10,1))
zp1

array([[ 35],
       [ 45],
       [190],
       [200],
       [ 40],
       [ 70],
       [ 54],
       [150],
       [120],
       [110]])

In [7]:
ks1 = ks.reshape((10,1 ))
ks1

array([[401],
       [574],
       [874],
       [919],
       [459],
       [739],
       [653],
       [902],
       [746],
       [832]])

In [8]:
zp1=np.hstack([np.ones((10,1)), zp1])

In [9]:
zp1

array([[  1.,  35.],
       [  1.,  45.],
       [  1., 190.],
       [  1., 200.],
       [  1.,  40.],
       [  1.,  70.],
       [  1.,  54.],
       [  1., 150.],
       [  1., 120.],
       [  1., 110.]])

In [10]:
b1 = np.dot(np.linalg.inv(np.dot(zp1.T,zp1)),zp1.T@ks1)

In [11]:
b1

array([[444.17735732],
       [  2.62053888]])

In [ ]:
y = 444.18 + 2.62*x

без использования intercept

In [12]:
zp2 = zp.reshape((10,1))
zp2

array([[ 35],
       [ 45],
       [190],
       [200],
       [ 40],
       [ 70],
       [ 54],
       [150],
       [120],
       [110]])

In [13]:
ks1 = ks.reshape((10,1 ))
ks1

array([[401],
       [574],
       [874],
       [919],
       [459],
       [739],
       [653],
       [902],
       [746],
       [832]])

In [18]:
b2 = np.dot(np.linalg.inv(np.dot(zp2.T,zp2)),zp2.T@ks1)
b2

array([[5.88982042]])

In [ ]:
ks = 5.89*zp

# 2

Посчитать коэффициент линейной регрессии при заработной плате (zp), используя градиентный спуск (без intercept).

In [34]:
def mse_(B1, y = ks, x = zp, n = 10):
    return np.sum((B1*x - y)**2) /n

In [35]:
alpha = 1e-6
alpha

1e-06

In [36]:
B1=0.1

In [37]:
n=10

In [45]:
for i in range(100):
    B1 -= alpha * (2/n) * np.sum((B1 * zp - ks) *zp)
    if i%10 == 0:
        print(f'B1 = {B1}, i = {i}, mse = {mse_(B1):.2f}')

B1 = 5.889820420132673, i = 0, mse = 56516.86
B1 = 5.889820420132673, i = 10, mse = 56516.86
B1 = 5.889820420132673, i = 20, mse = 56516.86
B1 = 5.889820420132673, i = 30, mse = 56516.86
B1 = 5.889820420132673, i = 40, mse = 56516.86
B1 = 5.889820420132673, i = 50, mse = 56516.86
B1 = 5.889820420132673, i = 60, mse = 56516.86
B1 = 5.889820420132673, i = 70, mse = 56516.86
B1 = 5.889820420132673, i = 80, mse = 56516.86
B1 = 5.889820420132673, i = 90, mse = 56516.86


# 3

В каких случаях для вычисления доверительных интервалов и проверки статистических гипотез используется таблица значений функции Лапласа, а в каких - таблица критических точек распределения Стьюдента? 

Таблица критических точек распределения Стьюдента применается когда неизвесто матеатическое ожидание и дисперсия генеральной совокупности, но мы знаем что величины распередены нормально.

Таблица значений функции Лапласа применяется для случаев когда мы знаем среднее и дисперсию генеральной совокупности и величины распеределены нормально.